{{- if .Values.emulator.enabled }}
apiVersion: v1
kind: Service
metadata:
  name: {{ include "inferno-cluster.fullname" . }}-emulator
  namespace: {{ .Values.global.namespace }}
  labels:
    {{- include "inferno-cluster.emulatorLabels" . | nindent 4 }}
spec:
  type: {{ .Values.emulator.serviceType }}
  selector:
    {{- include "inferno-cluster.emulatorSelectorLabels" . | nindent 4 }}
  ports:
    - name: styx
      port: {{ .Values.emulator.port }}
      targetPort: styx
      protocol: TCP
    {{- if .Values.monitoring.enabled }}
    - name: metrics
      port: {{ .Values.monitoring.metricsPort }}
      targetPort: metrics
      protocol: TCP
    {{- end }}
{{- end }}
