apiVersion: v1
kind: Service
metadata:
  name: inferno-registry
  namespace: inferno
  labels:
    app.kubernetes.io/name: inferno-registry
    app.kubernetes.io/component: registry
    app.kubernetes.io/part-of: inferno-cluster
spec:
  type: ClusterIP
  selector:
    app.kubernetes.io/name: inferno-registry
    app.kubernetes.io/component: registry
  ports:
    - name: styx
      port: 6675
      targetPort: styx
      protocol: TCP
    - name: metrics
      port: 9100
      targetPort: metrics
      protocol: TCP
